language: csharp
solution: Loyc.Binary.sln
install:
    # Restore NuGet packages first
    - make nuget
script:
    # Build the Loyc libraries in release mode.
    - make

    # Run the tests
    - make test
